pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapperLocations: classpath:mapper/**/*Mapper.xml

spring:

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html

  resources:
    static-locations: classpath:/static/,classpath:/templates/

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 180000

    #mysql config
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hzzy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

    #oracle config
    #driver-class-name: oracle.jdbc.OracleDriver
    #url: jdbc:oracle:thin:@192.168.1.1:1521:orcl
    #username: username
    #password: password


    #sqlServer config
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=test
    #username: sa
    #password: 123456

datasource:
    type: mysql